"""Shared helpers for emitters."""

from __future__ import annotations

import re
from pathlib import Path
from typing import List

from partest.project_gen.skeleton import WriteResult, _write


GENERATED_BANNER = (
    "# AUTO-GENERATED by partest-gen — do not edit by hand.\n"
    "# Re-run: partest-gen sync-openapi <project> --file <openapi>\n"
)


def is_snake(name: str) -> str:
    s = re.sub(r"(?<!^)(?=[A-Z])", "_", name or "")
    s = re.sub(r"[^a-zA-Z0-9_]+", "_", s)
    s = s.strip("_").lower()
    if not s:
        s = "unnamed"
    if s[0].isdigit():
        s = f"p_{s}"
    return s


def path_to_attr(path: str) -> str:
    """Turn OpenAPI path into a Python attribute name.

    /items            -> items
    /items/{id}       -> items_by_id
    /api/v1/clients   -> api_v1_clients
    """
    parts: List[str] = []
    for seg in (path or "").strip("/").split("/"):
        if not seg:
            continue
        if seg.startswith("{") and seg.endswith("}"):
            parts.append(f"by_{is_snake(seg[1:-1])}")
        else:
            parts.append(is_snake(seg))
    return "_".join(parts) or "root"


def class_name(tag: str, prefix: str = "Paths") -> str:
    parts = [p for p in is_snake(tag).split("_") if p]
    return prefix + "".join(p.capitalize() for p in parts)


def collection_class_name(tag: str) -> str:
    parts = [p for p in is_snake(tag).split("_") if p]
    base = "".join(p.capitalize() for p in parts) or "Common"
    # avoid double Collection
    if base.endswith("Collection"):
        return base
    return f"{base}Collection"


def write_file(
    root: Path,
    rel: str,
    content: str,
    *,
    force: bool,
    result: WriteResult,
    always: bool = False,
) -> None:
    """Write file. ``always=True`` overwrites generated artifacts even without force
    when the file is missing OR already carries the generated banner.
    """
    path = root / rel
    if always and path.exists() and not force:
        try:
            existing = path.read_text(encoding="utf-8")
            if GENERATED_BANNER.split("\n")[0] not in existing:
                result.skipped.append(rel.replace("\\", "/"))
                return
            # has banner — overwrite as sync
            force = True
        except OSError:
            pass
    _write(root, rel, content, force=force or always and not path.exists(), result=result)
    # if always and exists with banner, force write
    if always and path.exists():
        try:
            existing = path.read_text(encoding="utf-8")
            if GENERATED_BANNER.split("\n")[0] in existing or force:
                path.write_text(content, encoding="utf-8", newline="\n")
                rel_n = rel.replace("\\", "/")
                if rel_n not in result.created and rel_n not in result.skipped:
                    result.created.append(rel_n)
                elif rel_n in result.skipped and (
                    GENERATED_BANNER.split("\n")[0] in existing or force
                ):
                    result.skipped.remove(rel_n)
                    if rel_n not in result.created:
                        result.created.append(rel_n)
        except OSError:
            pass
